name: Developer Hub
markdown: redcarpet
#kramdown:
#  input: GFM

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data",  "no_intra_emphasis", "fenced_code_blocks"]

highlighter: pygments
safe: true
baseurl: /developers
exclude: ['.ruby-version', 'node_modules', 'package.json', 'bower.json']
sass:
  sass_dir: static/_sass

# Blog/Post configuration
paginate: 5
paginate_path: "blog/page:num"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      regs-name: "Regulations.gov"
      regs-url: "http://regulations.gov"
      regs-email: user@agency.gov
      regs-system: "Regulations"
      regs-dev-url: "https://github.com/regulationsgov/developers/"
      site-name: /developers
      source-code-policy.url: 
